#!/bin/bash
# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

cd $(dirname $0)

# Use DevEco Studio's hvigor directly
HVIGOR_SCRIPT="/Applications/DevEco-Studio.app/Contents/tools/hvigor/hvigor/bin/hvigor.js"
NODE_EXE="/Applications/DevEco-Studio.app/Contents/tools/node/bin/node"

if [ ! -f "${HVIGOR_SCRIPT}" ]; then
    echo "Error: Could not find DevEco Studio hvigor at ${HVIGOR_SCRIPT}"
    exit 1
fi

# Set environment variables
export HVIGOR_PROJECT_ROOT="$(pwd)"
export DEVECO_SDK_HOME="${DEVECO_SDK_HOME:-/Users/macmima1234/Library/OpenHarmony/Sdk/12}"
export hwsdk_dir="/Users/macmima1234/Library/OpenHarmony/Sdk/12"
export sdk_dir="/Users/macmima1234/Library/OpenHarmony/Sdk"
export nodejs_dir="/Applications/DevEco-Studio.app/Contents/tools/node"
export HVIGOR_INST_PATH="/Applications/DevEco-Studio.app/Contents/tools/hvigor"

# Execute hvigor
exec "${NODE_EXE}" "${HVIGOR_SCRIPT}" "$@"